In [23]:
import pandas as pd
from sqlalchemy.dialects.mssql.information_schema import columns

In [24]:
df = pd.read_csv(r"C:\Users\anand\PycharmProjects\PythonProject1\docs\extracted_resumes.csv")
df.head()

,text,metadata,jobclass
0,ACCOUNTANT\nSummary\nFinancial Accountant spec...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",ACCOUNTANT
1,STAFF ACCOUNTANT\nSummary\nHighly analytical a...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",ACCOUNTANT
2,ACCOUNTANT\nProfessional Summary\nTo obtain a ...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",ACCOUNTANT
3,SENIOR ACCOUNTANT\nExperience\nCompany Name Ju...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",ACCOUNTANT
4,SENIOR ACCOUNTANT\nProfessional Summary\nSenio...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",ACCOUNTANT

In [25]:
df.isnull().sum()

text        1
metadata    0
jobclass    0
dtype: int64

In [26]:
df = pd.get_dummies(df, columns=["jobclass"], prefix="jobclass")

In [27]:
df.head()

,text,metadata,jobclass_ACCOUNTANT,jobclass_ADVOCATE,jobclass_AGRICULTURE,jobclass_APPAREL,jobclass_ARTS,jobclass_AUTOMOBILE,jobclass_AVIATION,jobclass_BANKING,...,jobclass_DIGITAL-MEDIA,jobclass_ENGINEERING,jobclass_FINANCE,jobclass_FITNESS,jobclass_HEALTHCARE,jobclass_HR,jobclass_INFORMATION-TECHNOLOGY,jobclass_PUBLIC-RELATIONS,jobclass_SALES,jobclass_TEACHER
0,ACCOUNTANT\nSummary\nFinancial Accountant spec...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,STAFF ACCOUNTANT\nSummary\nHighly analytical a...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,ACCOUNTANT\nProfessional Summary\nTo obtain a ...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,SENIOR ACCOUNTANT\nExperience\nCompany Name Ju...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,SENIOR ACCOUNTANT\nProfessional Summary\nSenio...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [28]:
import re

def clean_text(t):
    t = re.sub(r"[ \t]+", " ", str(t))             # collapse spaces/tabs
    t = re.sub(r"\n\s*\n+", "\n\n", str(t))        # collapse blank lines to one
    t = re.sub(r"(?<!\n)\n(?!\n)", " ", str(t))    # join single line-breaks, keep doubles
    return t.strip()

df['text'] = df['text'].apply(clean_text)

In [29]:
df.head()

,text,metadata,jobclass_ACCOUNTANT,jobclass_ADVOCATE,jobclass_AGRICULTURE,jobclass_APPAREL,jobclass_ARTS,jobclass_AUTOMOBILE,jobclass_AVIATION,jobclass_BANKING,...,jobclass_DIGITAL-MEDIA,jobclass_ENGINEERING,jobclass_FINANCE,jobclass_FITNESS,jobclass_HEALTHCARE,jobclass_HR,jobclass_INFORMATION-TECHNOLOGY,jobclass_PUBLIC-RELATIONS,jobclass_SALES,jobclass_TEACHER
0,ACCOUNTANT Summary Financial Accountant specia...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,STAFF ACCOUNTANT Summary Highly analytical and...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,ACCOUNTANT Professional Summary To obtain a po...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,SENIOR ACCOUNTANT Experience Company Name June...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,SENIOR ACCOUNTANT Professional Summary Senior ...,"{'producer': 'Qt 4.8.7', 'creator': 'wkhtmltop...",True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False